name: Build Binaries

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@main
      with:
        submodules: 'recursive'
    - uses: microsoft/setup-msbuild@main
    - name: Clear local NuGet cache (workaround for failed restores on windows-latest)
      run: dotnet nuget locals all --clear
    - name: Refresh the build number
      run: MSBuild -target:RefreshVersion BuildAllTargets.proj
    - name: Prepare the compiled build tools binaries
      run: dotnet build --configuration Release NanaZip.Build.Tasks\NanaZip.Build.Tasks.csproj
    - name: Build
      run: MSBuild -binaryLogger:Output\BuildAllTargets.binlog -m BuildAllTargets.proj
    - name: Upload MSIX Bundle
      uses: actions/upload-artifact@main
      with:
        name: NanaZip_Mainline_ApplicationPackages
        path: Output/Binaries/AppPackages
    - name: Upload Extension Package Installer
      uses: actions/upload-artifact@main
      with:
        name: NanaZip_Mainline_ExtensionPackageInstaller
        path: Output/NanaZip.ExtensionPackage_*.exe
    - name: Upload MSBuild Build Process Binary Log
      uses: actions/upload-artifact@main
      if: '!cancelled()'
      with:
        name: NanaZip_Mainline_BuildBinaryLog
        path: Output/BuildAllTargets.binlog
